### ISSUE TITLE
Install new org in EVM 25.x

### ISSUE THREAD

**Issue by seagle0128** [rejeep/evm#116]
While I test on EVM 25.x, I found it installed the latest org while not using the built-in `org`. But it never happens on other versions, including 26.1 and 27.0. I am sure I didn't install the latest org in my configurations. Can you check and let me know how to avoid this issue? Thanks.

e.g. https://travis-ci.org/seagle0128/.emacs.d/jobs/479496883

**Comment by sambrightman** [comment]
I am closing this for now, since it's not clear what is going wrong or why it would be EVM's fault (the attached build log is rather verbose and times out rather than failing with anything `org-mode`-related that I can see. Feel free to re-open if you have some a clear, minimal example of what is wrong with 25.3.
