### ISSUE TITLE
Emacs 26.x-travis images can't determine version of Emacs

### ISSUE THREAD

**Issue by gcentauri** [rejeep/evm#134]
I'm very new to EVM, and am trying to update the travis config in the minitest-emacs repo https://github.com/arthurnn/minitest-emacs/pull/46 ... so far so good, except that the versions of Emacs 26 that aren't the `linux-xenial` images are failing: 

![image](https://user-images.githubusercontent.com/760104/70840432-dbbd1e80-1dd7-11ea-8ad4-ab398c580ff4.png)

They're all complaining that cask cant find the verson of Emacs at emacs:

![image](https://user-images.githubusercontent.com/760104/70840451-fdb6a100-1dd7-11ea-9a01-39de76ec71de.png)

I'm wondering if it has something to do with gpg keys in those other versions? I'm happy to help debug this and improve it, but maybe its something in my own configuration I'm missing.

**Comment by liblit** [comment]
Travis's default Ubuntu images now use Xenial. Unfortunately the existing `emacs-26.x-travis` builds do not work under Xenial due to a missing `libgnutls.so.26` shared library. Switch to using `emacs-26.x-travis-linux-xenial` instead and this problem should go away. Note that this only affects Emacs 26._x_, which is why your Emacs 24._x_ and Emacs 25._x_ jobs still succeed.

**Comment by gcentauri** [comment]
Thanks for the answer! I will just remove the default images from the CI list.
